### ISSUE TITLE
Compiling to JavaScript

### ISSUE THREAD

**Issue by ForbesLindesay** [nodeconf/london#3]
The range of programming languages that compile to JavaScript is enormous.  From brand new languages like Coffee Script, to tempting languages like Jade all the way to pre-existing languages like F# and Java. It seems like everyone wants to use JavaScript as a compile target these days. This talk will cover all the steps to writing a clear, well structured compiler in JavaScript. It will also discuss a few optimisations you may want to perform, using Jade as an example.

**Comment by mikeal** [comment]
Great topic, but I'd like to know what the story is going to be? Are you planning on walking through the process of creating a compiler?  Are you going to tell the story of commonly known compilers? It's important to have semi-narrative structure in order to keep the talk within 20 minutes because it helps you cut things that don't fall into the narrative :)

**Comment by ForbesLindesay** [comment]
Sorry, this just got buried in other GitHub issues.  I'd like to walk through the process of writing a compiler, starting with how to build a lexer to convert a string of text into a stream of tokens, moving on to how you can convert that stream of tokens into an abstract syntax tree by building a parser, then how to generate JavaScript from that abstract syntax tree.  Focusing on jade as an example for each of those steps.  Time permitting I'd then talk about how you could apply different optimisations both before and after the generate stage.
